### ISSUE TITLE
[REQUEST] fio 3.31 Windows

### ISSUE THREAD

**Issue by dsm** [JonMagon/KDiskMark#87]
Beginning with fio 3.31 Windows installers are available on GitHub at https://github.com/axboe/fio/releases can we support Windows OS ?

**Comment by dsm** [comment]
any progress ?  latest appimage with fio 3.32 and i think fio support windows and why we can't support ?

**Comment by MeowKatee** [comment]
To support windows, we need to:

1. set `windowsaio` as default ioengine for windows, `libaio` for linux
2. port everything related to unix/linux to windows

https://github.com/JonMagon/KDiskMark/blob/cfeadf2a9de08d228b2575f40f70d335c044ba55/src/diskdriveinfo.cpp#L18-L46

**Comment by mokurin000** [comment]
Hi, I wrote a helper tool in rust, outputs yaml:

```yaml
disk:
    index: 0
    model: Predator SSD GM7000 2TB
    serial: 0000_0000_0000_0000_A843_9732_9020_2003.
    drive:
    - type: drive
      name: C
      space: 504.61 GiB/1.36 TiB

    - type: volume
      name: \\?\Volume{97a22e68-4cde-4f09-a328-cd6af09ffedd}\
      space: 504.61 GiB/1.36 TiB

    - type: volume
      name: \\?\Volume{d884e958-f104-49b9-b92f-02079fa75d83}\
      space: 68.91 MiB/1017.00 MiB
```

This maybe helpful to list disks and drives, freespace
