### ISSUE TITLE
Flatpak request

### ISSUE THREAD

**Issue by skobkin** [JonMagon/KDiskMark#98]
I saw that Flatpak was also requested in #34, but it wasn't implemented, so I'm leaving this feature request here.
Flatpak is available on some platforms where store app does not support backends like Snap or AppImage.
Good example is SteamOS 3 on Steam Deck where only Flatpak is available.

**Comment by JonMagon** [comment]
AppImage should work on SteamOS

**Comment by skobkin** [comment]
It works, but it's not installable via Discover and couldn't be auto-updated there.

**Comment by JonMagon** [comment]
Well that makes sense. Although I was somewhat hopeful that the person in that issue would package. It will take me some time to get to grips with flatpack, as I'm not really a snap or flatpack amateur.

**Comment by JonMagon** [comment]
It seems to be working.
```yaml
app-id: dev.jonmagon.kdiskmark
runtime: org.kde.Platform
runtime-version: '5.15-21.08'
sdk: org.kde.Sdk
command: kdiskmark
finish-args:
  - --socket=x11
  - --socket=wayland
  - --filesystem=host
  - --device=dri
modules:
  - name: kdiskmark
    buildsystem: cmake-ninja
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DROOT_EDITION=OFF
    sources:
      - type: git
        url: https://github.com/JonMagon/KDiskMark.git
        commit: b411c4ae0d4a4ab23531ae1fecddcf76a493a515
        x-checker-data:
          type: git
    modules:
      - name: fio
        buildsystem: simple
        build-commands: 
          - ./configure --prefix=$FLATPAK_DEST
          - make -j $FLATPAK_BUILDER_N_JOBS
          - make install
        sources:
          - type: git
            url: https://github.com/axboe/fio.git
            tag: fio-3.32
            commit: db7fc8d864dc4fb607a0379333a0db60431bd649
            x-checker-data:
              type: git
        modules:
          - name: libaio
            buildsystem: simple
            build-commands: 
              - make prefix=$FLATPAK_DEST install
            sources:
              - type: git
                url: https://pagure.io/libaio.git
                tag: libaio-0.3.113
                commit: 1b18bfafc6a2f7b9fa2c6be77a95afed8b7be448
                x-checker-data:
                type: git
```
